Repository jenkinsci/plugin-installation-manager-tool, pull requests merged in 2019-07, with the labels that each got.

#50 plugin might not be in the update center json
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
Labels: fix

#49 Parallel downloading
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
Labels: enhancement

#51 Bump version
  pom.xml
Labels: skip-changelog

#52 Try re-enable incrementals
  .mvn/extensions.xml
  .mvn/maven.config
Labels: chore

#53 Use version not revision for lib
  plugin-management-cli/pom.xml
Labels: chore

#54 [no merge] Fix incrementals
  .mvn/maven.config
  Jenkinsfile
  plugin-management-cli/pom.xml
  plugin-management-library/pom.xml
  pom.xml
Labels: chore

#56 Update jar name - post incrementals cleanup
  README.md
  plugin-management-cli/pom.xml
Labels: chore
