Repository jenkinsci/plugin-installation-manager-tool, pull requests merged in 2020-12, with the labels that each got.

#232 Add support for a Jenkins version argument (CLI and env var) + Make Jenkins WAR parameter optional in the Plugin Manager Lib API and the implementation
  README.md
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/CliOptions.java
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/Main.java
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/VersionNumberHandler.java
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/config/Config.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: enhancement

#239 Stop cleaning the plugin directory by default, add an opt-in flag for doing so
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/CliOptions.java
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/Main.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/config/Config.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/ManifestTools.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerIntegrationTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: bug, enhancement

#241 Improve plugin list entries in the --list command
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: enhancement

#240 Ensure that the Jenkins core versions requirements are properly checked for plugins without dependencies
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
Labels: bug

#243 Add support for exploded plugin directories
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/CacheManager.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/ManifestTools.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/PluginManagerUtils.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/CacheManagerTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerIntegrationTest.java
Labels: enhancement

#246 Fix typo in PluginManager.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
Labels: bug

#248 flat map the nested collect list.
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
Labels: bug
