Repository jenkinsci/plugin-installation-manager-tool, pull requests merged in 2020-06, with the labels that each got.

#94 Add caching + remove -plugin retry hack + fix master
  README.md
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/config/Settings.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/CacheManager.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/MockCacheManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: bug, enhancement

#102 Do not iterate through transient plugin dependencies if a newer dependency version is explicitly defined in the plugin list
  .gitignore
  plugin-management-library/pom.xml
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/Plugin.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerIntegrationTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/impl/plugin-versions.zip
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/impl/plugins.txt
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/impl/updates.zip
Labels: bug, squash-merge-me

#105 Move plugin list parser to the library JAR
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/CliOptions.java
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/URLValidatorTest.java
  plugin-management-library/pom.xml
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/config/PluginInputException.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/PluginListParser.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/util/PluginListParserTest.java
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/util/PluginListParserTest/badformat1.yaml
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/util/PluginListParserTest/badformat2.yaml
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/util/PluginListParserTest/badformat3.yaml
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/util/PluginListParserTest/plugins.txt
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/util/PluginListParserTest/plugins.yaml
Labels: chore

#106 Add environmenet variable for overriding plugin info location + document proxy configuration
  README.md
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/CliOptions.java
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/config/Config.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/config/Settings.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
Labels: documentation, enhancement

#107 Remove alpha from release drafter
  .github/release-drafter.yml
Labels: chore

#110 Bump parent
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/CliOptions.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  pom.xml
Labels: chore

#111 Update tag template
  .github/release-drafter.yml
Labels: chore

#112 Update cli file name in README
  README.md
Labels: chore
