Repository jenkinsci/plugin-installation-manager-tool, pull requests merged in 2020-09, with the labels that each got.

#184 Fix 'latest' with deps error
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerIntegrationTest.java
Labels: bug

#185 Remove unneeded additional CI (windows java8)
  Jenkinsfile
Labels: chore

#186 Automate GitHub release publishing
  .github/workflows/publish-release-artifact.yml
Labels: chore

#187 Set tag name format to just be the project version
  .github/release-drafter.yml
  pom.xml
Labels: chore

#192 Add `JENKINS_UC_DOWNLOAD`, allows overriding plugin download URL
  README.md
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
Labels: enhancement
