Repository jenkinsci/plugin-installation-manager-tool, pull requests merged in 2020-07, with the labels that each got.

#114 Make yaml parsing type safe
  plugin-management-cli/src/test/resources/plugins.yaml
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/PluginInfo.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/PluginListParser.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/Plugins.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/Source.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/util/PluginListParserTest.java
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/util/PluginListParserTest/plugins.txt
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/util/PluginListParserTest/plugins.yaml
Labels: enhancement

#117 Use varargs for convertig plugins to Strings
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: chore

#116 Use System Lambda instead of System Rules
  plugin-management-library/pom.xml
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerIntegrationTest.java
Labels: chore

#118 Create lists with asList and singletonList
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/util/PluginListParserTest.java
Labels: chore

#119 Fix test "checkVersionCompatibilityPassTest"
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: chore

#120 Tidy up test "checkVersionCompatibilityNullTest"
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: chore

#121 Use assertThrows for checking exceptions
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/util/PluginListParserTest.java
Labels: chore

#123 Tap System.out with System Lambda
  plugin-management-cli/pom.xml
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: chore

#124 Don't mock Files.exists
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/util/PluginListParserTest.java
Labels: chore

#125 Use SystemLambda's "withEnvironmentVariable"
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
Labels: chore

#126 Extract method "assertConfigHasPlugins"
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
Labels: chore

#127 Verify that version is shown without PowerMock
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
Labels: chore

#128 Assert list of Plugins instead of Strings
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: chore

#129 Don't mock Config
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: chore

#131 Use JSONTokener for reading JSON from file
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/CacheManager.java
Labels: chore

#130 TemporaryFolder creates parent dir of plugin dir
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: chore

#132 Use real CacheManager instead of a mock
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/MockCacheManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: chore

#134 Use AssertJ for assertions
  plugin-management-cli/pom.xml
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/URLValidatorTest.java
  plugin-management-library/pom.xml
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerIntegrationTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/util/PluginListParserTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/util/PluginManagerUtilsTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/util/URIStringBuilderTest.java
  pom.xml
Labels: chore

#133 Remove Comparable interface from Plugin
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/Plugin.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
Labels: chore

#137 Add additional tests for CacheManager
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/CacheManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/CacheManagerTest.java
Labels: chore

#138 Only write cache files with valid JSON objects
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/CacheManager.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/CacheManagerTest.java
Labels: bug

#139 Delete unused code
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: chore

#140 Enable dependabot
  .github/dependabot.yml
Labels: chore

#147 Extract methods for creating JSON objects
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: chore

#148 Replace PowerMock with Wiremock
  plugin-management-library/pom.xml
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerWiremockTest.java
  plugin-management-library/src/test/resources/mappings/2235_update-centeractualjson-41c3663c-165f-4d27-81d9-ee7e764fd9ba.json
  plugin-management-library/src/test/resources/mappings/2235_update-centeractualjson-de830c32-255e-457d-897b-7336cd95c5b6.json
  plugin-management-library/src/test/resources/mappings/plugins_mailer_132_mailerhpi-1752ca16-5c58-4e2f-8b70-6b0a37d2b1d1.json
  plugin-management-library/src/test/resources/mappings/plugins_mailer_132_mailerhpi-fed8de84-95ac-4fe6-b710-29dd607ccf05.json
  pom.xml
Labels: tests

#156 Make --latest the default
  .gitignore
  README.md
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/CliOptions.java
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
Labels: breaking, enhancement

#149 Add API for showing available updates
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerUpdatesTest.java
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/impl/available-updates/simple-plugin-versions.json
Labels: enhancement

#155 Add outputting available updates
  README.md
  plugin-management-cli/pom.xml
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/CliOptions.java
  plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/Main.java
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
  plugin-management-cli/src/test/resources/plugins.t
  plugin-management-cli/src/test/resources/plugins.txt
  plugin-management-cli/src/test/resources/plugins.yaml
  plugin-management-library/pom.xml
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/config/Config.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/config/OutputFormat.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/CacheManager.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/parsers/PluginOutputConverter.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/parsers/StdOutPluginOutputConverter.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/parsers/TxtOutputConverter.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/parsers/YamlPluginOutputConverter.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/PluginInfo.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/PluginListParser.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/Plugins.java
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/Source.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/parsers/BaseParserTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/parsers/StdOutPluginOutputConverterTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/parsers/TxtOutputConverterTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/parsers/YamlPluginOutputConverterTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/util/PluginListParserTest.java
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/util/PluginListParserTest/plugins.txt
  plugin-management-library/src/test/resources/io/jenkins/tools/pluginmanager/util/PluginListParserTest/plugins.yaml
Labels: enhancement

#159 Fail if top level requests lower version than required dependency
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerIntegrationTest.java
Labels: breaking, bug
