Repository jenkinsci/plugin-installation-manager-tool, pull requests merged in 2023-07, with the labels that each got.

#576 feat: sort the YAML output by name and version
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/parsers/YamlPluginOutputConverter.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: enhancement

#578 chore(GHA) use `gh` CLI to publish artefact to release
  .github/workflows/publish-release-artifact.yml
Labels: bug

#582 Update HtmlUnit package for JaCoCo
  pom.xml
Labels: tests

#583 Test on Java 17
  Jenkinsfile
  plugin-management-cli/src/test/java/io/jenkins/tools/pluginmanager/cli/CliOptionsTest.java
  plugin-management-library/src/test/java/io/jenkins/tools/pluginmanager/impl/PluginManagerTest.java
Labels: tests
