Repository jenkinsci/plugin-installation-manager-tool, pull requests merged in 2023-02, with the labels that each got.

#524 Enable ci.jenkins.io coverage reporting
  plugin-management-cli/pom.xml
  plugin-management-library/pom.xml
  pom.xml
Labels: chore

#526 Fix publish release artifact GitHub action
  .github/workflows/publish-release-artifact.yml
Labels: bug

#528 Add --clean-download-directory to README.md
  README.md
Labels: documentation

#536 Add a contributing guide
  CONTRIBUTING.md
  README.md
Labels: documentation
