Repository jenkinsci/plugin-installation-manager-tool, pull requests merged in 2024-05, with the labels that each got.

#675 Add SHA256 checksum to GitHub release
  .github/workflows/publish-release-artifact.yml
Labels: enhancement

#676 Stop storing the filename inside the `.sha256` file
  .github/workflows/publish-release-artifact.yml
Labels: bug

#679 Only resolve experimental update center if required
  plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java
Labels: enhancement

#683 Remove explicit snakeyaml dependency
  plugin-management-library/pom.xml
Labels: chore
